---
title: "methods"
author: "Rouven Schmidt"
date: "4/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Statistical Model
To answer the research question, we consider the effect of AirBnBs on the Housing Price. The housing price is logarithmes to map the support of the random variable to the whole real line. For the model density is choosen as beeing the most important independent variable of the model. Density is considered a more informative information as distance. Thus distance is only utilized as a control variable. 
The applied method is a general additive model (GAM). The dependent variable $log(price_{it})$ with $i=1,...,n$ is assumed to follow a scaled t distribution (Wood, S.N., N. Pya and B. Saefken (2016) , Smoothing parameter and model selection for general smooth models. Journal of the American Statistical Association 111, 1548-1575 doi: ). The distribution is useful in place of Gaussian distribution, when the data are heavy tailed. The model equation is as follows:

\[
E(log(price_{it})) = \beta_0 + \beta_1 wtype_{it}  + \beta_2 construction\_period_{it} + \beta_3 garden_{it} + \\
          \beta_4 size_{it} + \beta_5 parking_{it} + \beta_6 monumentalstatus_{it} + \beta_7 buyerpaysorfree_{it} + \\
          \beta_8 quality_{it} + \beta_9 gdp\_change_{it} + \beta_10 accomodation\_nl\_change_{it} + \beta_11 population_{it}\\
          \alpha_{t} pc4_{it} +
          f_1(denstiy_{it}) +
          f_2(time_{it})
          
\]

where, one has to consider, that the categorial variables $wtype,construction\_period, garden, parking, monumentalstatus, buyerpaysorfree$ and  $quality$ are dummy coded, thus resulting in multiple $\beta$. These are neglected for ease of notation, in the above equation. The non-linear functions $f_j$ for $j \in \{1,2\}$ are approximated using p-splines of the form: 
\[
f_j(z_j)=\sum_{l=1}^{d_j} \gamma_{jl} B_l(z_j)
\]
where $d_j$ is the number dimension of the basis used to represent the smooth.
It is often assumed that the function that models the dependence between dependent and independent variable elongs to a parametric family of functions. This is quite restrictive and can lead to a serious modelling bias resulting in misleading conclusions about the link between independent and dependent variables (Giannakas et al., 2003). Thus the more general and flexible approach of penalized b-splines was choosen.


Further, the effect of $pc4$ is modelled as a random effect with $pc4_t \sim N(0,\sigma_\gamma)$. This is so one can leanr about the 
For more details see Generaliyed Additive Models an Introduction with R.
The model can be estimated via maximum likelihood estimation. The \textit{mgcv} package by Simon Wood was used.




